### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by Myzxfrl** [FalseKSCH/Thief-Cat#1]
When I try to run the file it won’t send me the info

**Comment by lolk11** [comment]
send me your discord

**Comment by lolk11** [comment]
> When I try to run the file it won’t send me the info

send me your discord

**Comment by Myzxfrl** [comment]
No hash tag add me as soon as ya can

**Comment by Myzxfrl** [comment]
> > When I try to run the file it won’t send me the info
> 
> send me your discord

It’s iluvdogslol
