### ISSUE TITLE
can someone help me set it up for use? would be nice

### ISSUE THREAD

**Issue by noclap077** [FalseKSCH/Thief-Cat#6]

**Comment by FalseKSCH** [comment]
hey do you have any error/problem?

**Comment by noclap077** [comment]
Yeah, I'm not a lot into commands and stuff is there a noobie guide how to install it step by step ?

**Comment by FalseKSCH** [comment]
I will create a doc for you

**Comment by noclap077** [comment]
Thx I would appreciate that

**Comment by noclap077** [comment]
Do you wanna have my Discord? So you can send the docu

**Comment by Qweurs1** [comment]
I would also like detailed instructions. can you please provide it. Thank you )

**Comment by Iamjustacrab** [comment]
can I get some instructions too pls

**Comment by FalseKSCH** [comment]
https://gist.github.com/FalseKSCH/d6e082638fc182d2a337caebe2ba007a

**Comment by FalseKSCH** [comment]
good

**Comment by noclap077** [comment]
Thx
