### ISSUE TITLE
can I please get some instructions

### ISSUE THREAD

**Issue by Iamjustacrab** [FalseKSCH/Thief-Cat#8]
Im not really into coding and couldnt figure out how to do this 
my nick is: lucixa_

**Comment by FalseKSCH** [comment]
https://gist.github.com/FalseKSCH/d6e082638fc182d2a337caebe2ba007a

**Comment by Iamjustacrab** [comment]
![image](https://github.com/FalseKSCH/Thief-Cat/assets/131277096/cc8c9dbb-a4f9-479f-85e4-e012c3b2c7e1)
I keep getting this error when I start install.bat

**Comment by Iamjustacrab** [comment]
I do 
I have three actually :P python 3.8, 3.10, 3.11
